# Generated by Django 4.1.2 on 2023-01-16 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_usersubmittedanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='time_limit',
        ),
    ]
