# Generated by Django 4.1.2 on 2023-01-16 12:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0007_usercategoryanswer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCategoryAnswer',
            new_name='UserCategoryAttempts',
        ),
    ]
