# Generated by Django 4.1.2 on 2023-01-16 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_rename_attempt_usercategoryattempts_attempt_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCategoryAttempts',
        ),
    ]
