# Generated by Django 4.1.2 on 2023-01-16 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_usercategoryattempts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCategoryAttempts',
        ),
    ]
